project:
  type: website

website:
  title: "Sensitive and Qualitative Data"
  site-url: https://RicCampbell.github.io/rdm_sensitive_data_slides
  description: "Slides to be used for the sensitive and qualitative training sessions by the Univerity Library"
